@startuml


interface HttpMessage{
+ protocolVersion()
+ headers()
}

interface HttpRequest{
+ method()
+ uri()
}
interface FullHttpMessage {
}
interface HttpResponse{
+ status()
}
interface LastHttpContent {
+ trailingHeaders()
}


interface FullHttpRequest {
}
interface FullHttpResponse {
}



HttpMessage                      <|--          HttpRequest
HttpMessage                      <|--          HttpResponse


HttpMessage                     <|--          FullHttpMessage
LastHttpContent                     <|--          FullHttpMessage
FullHttpMessage                     <|--          FullHttpRequest
HttpRequest                     <|--          FullHttpRequest
FullHttpMessage                     <|--          FullHttpResponse
HttpResponse                     <|--          FullHttpResponse

@enduml
