@startuml


interface Headers{
}
interface HttpHeaders{
+ getAsString()
+ getAllAsString()
+ iteratorAsString()
+ contains()
}
class DefaultHeaders{
}
class EmptyHeaders{
}
class DefaultHttpHeaders{
}
class EmptyHttpHeaders{
}
class CombinedHttpHeaders{
}
class TrailingHttpHeaders{
}



Headers                      <|--          HttpHeaders
DefaultHeaders                      <|--          DefaultHttpHeaders
HttpHeaders                      <|--          DefaultHttpHeaders
EmptyHeaders                      <|--          EmptyHttpHeaders
HttpHeaders                      <|--          EmptyHttpHeaders
DefaultHttpHeaders                      <|--          CombinedHttpHeaders
DefaultHttpHeaders                      <|--          TrailingHttpHeaders

@enduml
