@startuml

interface DecoderResultProvider{
+ DecoderResult decoderResult()
+ void setDecoderResult()
}
interface HttpObject{
}
interface HttpMessage{
+ HttpVersion protocolVersion()
+ HttpMessage setProtocolVersion(HttpVersion version)
+ HttpHeaders headers()
}
class DefaultHttpObject{
}
interface HttpObject{
}
interface HttpRequest{
+ HttpMethod method()
+ String uri()
}
interface FullHttpMessage{
}
interface FullHttpRequest{
}
interface FullHttpResponse{
}
interface HttpResponse{
}
interface HttpContent{
+ HttpVersion protocolVersion()
+ HttpMessage setProtocolVersion(HttpVersion version)
+ HttpHeaders headers()
}
class DefaultHttpMessage{
}
interface LastHttpContent {
}
class DefaultHttpContent{
}
class DefaultLastHttpContent{
}
class DefaultHttpRequest{
}
class DefaultHttpRequest{
}
class DefaultFullHttpRequest{
}



DecoderResultProvider           <|--          HttpObject
HttpObject                      <|--          HttpMessage
HttpMessage                      <|--          HttpRequest
HttpMessage                      <|--          HttpResponse
HttpObject                      <|--          DefaultHttpObject
HttpObject                      <|--          HttpContent
HttpContent                     <|--          LastHttpContent
DefaultHttpObject               <|--          DefaultHttpContent
HttpContent                     <|--          DefaultHttpContent
DefaultHttpObject               <|--          DefaultHttpMessage
HttpMessage                     <|--          DefaultHttpMessage
DefaultHttpContent                     <|--          DefaultLastHttpContent
LastHttpContent                     <|--          DefaultLastHttpContent
DefaultHttpMessage                     <|--          DefaultHttpRequest
HttpRequest                     <|--          DefaultHttpRequest

HttpMessage                     <|--          FullHttpMessage
LastHttpContent                     <|--          FullHttpMessage
FullHttpMessage                     <|--          FullHttpRequest
HttpRequest                     <|--          FullHttpRequest
FullHttpMessage                     <|--          FullHttpResponse
HttpResponse                     <|--          FullHttpResponse

@enduml
