@startuml

interface DecoderResultProvider{
+ decoderResult()
}
interface HttpObject{
}
interface HttpMessage{
+ protocolVersion()
+ headers()
}
interface HttpContent {
}
interface HttpRequest{
+ method()
+ uri()
}
interface HttpResponse{
}
interface FullHttpMessage{
}
interface FullHttpRequest{
}
interface FullHttpResponse{
}


interface LastHttpContent {
}



DecoderResultProvider           <|--          HttpObject
HttpObject                      <|--          HttpMessage
HttpMessage                      <|--          HttpRequest
HttpMessage                      <|--          HttpResponse
HttpObject                      <|--          HttpContent
HttpContent                     <|--          LastHttpContent



HttpMessage                     <|--          FullHttpMessage
LastHttpContent                     <|--          FullHttpMessage
FullHttpMessage                     <|--          FullHttpRequest
HttpRequest                     <|--          FullHttpRequest
FullHttpMessage                     <|--          FullHttpResponse
HttpResponse                     <|--          FullHttpResponse

@enduml
